version: "3.9"

services:
  app:
    build:
      context: .
      args:
          reqFile: requirements-dev.txt
    volumes:
      - .:/app
    expose:
      - "8000"
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
volumes:
  db_data:
