version: "3.9"

services:
  celery: &celery
    build:
      context: .
      args:
          reqFile: requirements-dev.txt
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    command: "celery -A onlineShop worker -l info"
    depends_on:
      - db
      - redis
      - rabbitMQ

  flower:
    <<: *celery
    command: "celery -A onlineShop flower"
    environment:
      - FLOWER_BROKER_API=http://guest:guest@rabbitMQ:15672/api/
    ports:
      - 5555:5555
    depends_on:
      - celery
  app:
    <<: *celery
    command: "python manage.py runserver 0.0.0.0:8000"
    expose:
      - "8000"
    ports:
      - 8000:8000

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  rabbitMQ:
    image: rabbitmq:3-management
    expose:
      - 5672
      - 15672
    ports:
      - 15672:15672




volumes:
  db_data:
